version: '3.7'

networks:
  kafka_cluster:
    external: true

services:
  # ------------------------------------------------------------
  # HAProxy Load balancer in front of Kong Gateway.
  # ------------------------------------------------------------
  haproxy:
    image: haproxy:2.5.5-alpine
    container_name: haproxy
    networks:
      kafka_cluster:
        aliases:
        - haproxy
        ipv4_address: 192.168.1.14
    restart: always
    # command: haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "9092:9092"
      - "9093:9093"
      - "1936:1936"
    volumes:
      - ./haproxy-conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      kafka_cluster:
        ipv4_address: 192.168.1.13
    ports:
      - 9000:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    