version: '3.7'

networks:
  kafka_cluster:
    external: true

services:
  producer:
    platform: linux/amd64
    container_name: producer
    image: ruanbekker/kafka-producer-consumer:2023-05-17
    # source: https://github.com/ruanbekker/quick-starts/tree/main/docker/kafka/python-client
    restart: always
    environment:
      - ACTION=producer
      # - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - BOOTSTRAP_SERVERS=haproxy:9092
      - TOPIC=my-topic
      - PYTHONUNBUFFERED=1 # https://github.com/docker/compose/issues/4837#issuecomment-302765592
    networks:
      - kafka_cluster
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  consumer:
    platform: linux/amd64
    container_name: consumer
    image: ruanbekker/kafka-producer-consumer:2023-05-17
    # source: https://github.com/ruanbekker/quick-starts/tree/main/docker/kafka/python-client
    restart: always
    environment:
      - ACTION=consumer
      # - BOOTSTRAP_SERVERS=haproxy:8881,haproxy:8882,haproxy:8883,haproxy:8884,haproxy:8885,haproxy:8886
      - BOOTSTRAP_SERVERS=haproxy:8881,haproxy:8882,haproxy:8883
      - TOPIC=my-topic
      - CONSUMER_GROUP=cg-group-id
      - PYTHONUNBUFFERED=1 # https://github.com/docker/compose/issues/4837#issuecomment-302765592
    networks:
      - kafka_cluster
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    